return {
  {
    "nvim-neo-tree/neo-tree.nvim",
    branch       = "v3.x",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-tree/nvim-web-devicons",
      "MunifTanjim/nui.nvim",
    },
    cmd = { "Neotree" },
    opts = {
      close_if_last_window    = true,
      popup_border_style      = "rounded",
      enable_git_status       = true,
      enable_diagnostics      = true,
      default_component_configs = {
        indent = {
          indent_size   = 2,
          with_markers  = true,
          with_expanders = true,
        },
        git_status = {
          symbols = {
            added     = "",
            modified  = "",
            deleted   = "✗",
            renamed   = "➜",
            untracked = "★",
            ignored   = "◌",
            unstaged  = "✗",
            staged    = "✓",
            conflict  = "",
          },
        },
      },
      window = {
        position = "left",
        width    = 35,
        mappings = {
          ["<space>"] = "toggle_node",
          ["<cr>"]    = "open",
          ["s"]       = "open_split",
          ["v"]       = "open_vsplit",
          ["t"]       = "open_tabnew",
          ["P"]       = { "toggle_preview", config = { use_float = true } },
          ["C"]       = "close_node",
          ["z"]       = "close_all_nodes",
          ["R"]       = "refresh",
          ["a"]       = { "add", config = { show_path = "relative" } },
          ["d"]       = "delete",
          ["r"]       = "rename",
          ["y"]       = "copy_to_clipboard",
          ["x"]       = "cut_to_clipboard",
          ["p"]       = "paste_from_clipboard",
          ["q"]       = "close_window",
          ["?"]       = "show_help",
        },
      },
      filesystem = {
        filtered_items = {
          visible       = false,
          hide_dotfiles = false,
          hide_gitignored = true,
        },
        follow_current_file = { enabled = true },
        use_libuv_file_watcher = true,
      },
    },
  },
}
